import { type NextPage } from "next";
import Head from "next/head";
import PageLayout from "~/components/PageLayout";

import { META_TITLE } from "~/utils/constants";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>{META_TITLE}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <section className="mt-5">
          <h1>Welcome</h1>
        </section>
      </PageLayout>
    </>
  );
};

export default Home;
